name: My First Action

on: 
  push:  # This triggers the action when code is pushed

jobs:
  my-job:  # Name of the job
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # GitHub's official action to check out code

      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"  # Prints a simple message

      - name: Check Internet Connectivity
        run: curl -I https://www.google.com

